deploy:
  stage: deploy
  environment: production
  only:
    - master
  script: |
    lftp -c "set sftp:auto-confirm yes && $CONNECTION_MAGIC && mirror --reverse --delete --verbose $PWD/public httpdocs && quit"
